cards powerful-features
lucasmassei/LP pull request #1
Opened 2021-01-22 15:18 UTC by lucasmassei

2021-01-22 18:13 UTC, gqueiroz1 requested changes

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +<!DOCTYPE html>
Primeira coisa que vamos fazer aqui é otimizar as imagens.
Por que otimizar?
O tempo de carregamento de uma página depende diretamente do tamanho dos arquivos que precisam ser baixados/carregados durante a execução. 
As imagens são uma das primeiras coisas que baixamos quando acessamos um site, se isso for pesado o tempo de download será maior, consequentemente o site ficará lento e pode ocasionar na perda de usuários.

Pra otimizar hoje utilizamos duas maneiras. A primeira vamos usar o formato mais comum de imagens otimizadas que é o .PNG.
A segunda, vamos transformar nossos pngs em .webp. WebP é um formato relativamente novo na web que consiste em uma imagem mais enxuta (em seu arquivo binário) e que consegue manter a qualidade, reduzindo assim drasticamente o tamanho e tempo de carregamento. Porém não são todos os navegadores que suportam, hoje grande parte já suporta (os mais atualizados). 

A otimização terá de tratar isso, então vamos começar pelo PNG e posteriormente faço o webP com você.

Pra otimizar os pngs, vamos usar o [https://tinypng.com/](url)
Coloca a imagem lá e baixa ela otimizada, daí é só substituir no projeto. Compare com a original, vai ver que o tamanho é bem menor.
Feito isso os pngs já estão otimizados.
Pode manter as originais na pasta, vamos utilizar depois para os webP. Apenas troque os nomes para não confundir.

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +
Uma coisa pra gente sempre prestar atenção é a identação.
```
<body>
    <div>
        <h1>Olá Mundo</h1>
    </div>
</body>
```

Dessa forma é muito mais fácil percebermos que o nosso `h1` está dentro de uma `div` que está dentro do `body`

Corrigir identação

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +
Espaço desnecessário

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +    <div class="background">
As classes precisam ter uma semântica boa também. Os nomes precisam ser condizentes com o que aquela section ou elemento é responsável.

Aqui temos uma `div` englobando um título `h1`, um parágrafo `p` e um link `a`. 
Ela é responsável pela primeira section do site (primeira dobra ou seção). Possui um botão (link) CTA (Call to action).
Que tal nomear de `home-section` ?

Vamos também utilizar o HTML semântico. 
No html5, `div` é usada somente para separação de conteúdo. Não existe semântica alguma em `div`, apenas a função de denotar uma caixa.

Pra seguir com a semântica boa, sempre que iniciamos uma nova seção usamos a tag `<section>`. Dessa forma o navegador já entende que ali começa uma seção do seu site.
Pra dar nomes ao bois, usamos o `h1` e `h2`.
Por via de regra, o `h1` sempre será o título principal do site. No caso, o "LaunchPage".
Para essa primeira section podemos usar o `h1` e não mais.

Posteriormente quando tivermos novas sections utilizaremos o `h2`.
Uma dica é baixar a extensão do Chrome HTML5 Outline, que nos ajuda a ver como está a semântica do site.

![image](https://user-images.githubusercontent.com/22224160/105519900-c859d380-5cb8-11eb-8216-4d4bccce34c6.png)

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +     <h1 class="title1">LaunchPage</h1>
Continuando com o nome das classes, como esse é o título da `home-section`, que tal chamar a classe de `home-section-title` ?

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +     <p class="text1">Proudly introducing the ultimate landing page template. LaunchPage is everything you will need to create your unique landing page.</p>
Aqui é um texto de descrição, que tal `home-section-description` ?

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +     <a href="#" class="button">Purchase LaunchPage</a>
E aqui é um link de um Call To Action, que tal `home-section-cta` ?

![image](https://user-images.githubusercontent.com/22224160/105520190-24245c80-5cb9-11eb-9fd2-cfe115060985.png)

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +
Espaço desnecessário

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +    <div class="position">
Para essa seção vamos precisar reestruturar o html.
![image](https://user-images.githubusercontent.com/22224160/105520440-7cf3f500-5cb9-11eb-9c81-5ab7a93ee4a6.png)

Choose Your Demo é uma seção que compreende um título, um subtítulo e os artigos.

Da forma como está estruturado, temos duas `divs` separadas fazendo duas seções quando deveríamos ter apenas uma.

Vamos refatorar a semântica. 

Para essa div `<div class="position">` vamos usar a tag `<section>` e alterar o nome da classe para `section-choose-demo`

A tag `section` irá fechar após todos os artigos, pois tudo isso faz parte da nossa seção.

Vamos renomear as classes de título e subtítulo também e usar o html5 semântico.
No lugar do `h1` vamos usar `h2` pois já temos um título principal.
No lugar do `p` podemos usar um `h3` para mantermos uma hierarquia de títulos.

```
 <h2 class="section-choose-demo-title">Choose Your Demo</h2>
 <h3 class="section-choose-demo-subtitle">4 Stunning Ready To Use Versions.</h3>
```

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +     <nav class="nav">
A tag `<nav>` é utilizada para navegações em menus para dentro do domínio. Geralmente utilizada em um `<header>`

Substitua essa tag por uma `div` para fazer a separação já que é apenas para abrigar um conteúdo dentro de uma caixa.

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +    </div>
Essa `</div>` deve sumir pois vamos fechar a seção com o `</section>` lá no final

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +      <div class="navitems">
HTML5 semântico novamente. Todo box de conteúdo que tivermos dentro de uma seção deve ser um `<article>`.

Renomeie também a classe seguindo os princípios das anteriores

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +         <a href="#" class="navitems-link">
Renomear classe

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +            <div class="navitems-overlay align-all-center flex"><img src="icon.png" /></div>
Renomear classe

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +            <img class="image" src="imagewoman.jpg">
Renomear classe

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +         <a href="#" class="subtitle">First Version</a>
Renomear classe

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +      <div class="navitems">
Faça os passos acima para todos os itens dessa seção

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +         <a href="#"><img class="image"src="imagegrouppeople1.jpg" /></a>
Lembrando que para esse fim aqui não é preciso uma tag `<a>` já que tudo é englobado por um link, pode substituir por `div` como foi feito acima

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +     <section class="section">
Renomear classe

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +      <div class="feature-card text-center">
Isso deve ser um `<article>` (box de conteúdo dentro de uma section)

2021-01-22 18:13 UTC, gqueiroz1 commented on index.html
> +         <img class="image2" src="imagebootstrap4.png">
HTML5 semântico, vamos passar uma propriedade `alt` para as imagens
` <img class="image2" src="imagebootstrap4.png" alt="Bootstrap 4">`

Essa propriedade cria um texto caso a imagem não possa ser exibida e também é utilizada pelos leitores de páginas dos buscadores. Dessa forma eles sabem do que se trata aquela imagem e mostram ao usuário com melhor ranqueamento.
Também é utilizado para acessibilidade, leitores de tela para cegos.

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  margin: 0px;
pode remover a margin e o padding aqui do body porque já passamos isso dentro do reset *

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 500px;
Não é muito usual setarmos um height para as sections.
O que podemos fazer é trabalhar com os espaçamentos internos que aquela caixa possui.
Se tudo estiver certinho, no fim o tamanho também estará. Portanto precisamos nos atentar às margins, aos paddings, ao tamanho de fonte, tamanho de imagens, etc.
A somatória disso nos dará o tamanho final da caixa que precisa estar fiel ao layout.

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 500px;
Pode remover esse `height` e vamos trabalhar com os espaçamentos mais fielmente, não tem problema se em um primeiro momento ficar errado. Você pode ir acertando isso colocando os espaçamentos nos elementos conforme o layout original

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.background {
`.background` é um nome bem genérico, né?
Ao ser alterado lá no html não esqueça de alterar aqui

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  align-items: center;
Podemos usar o DRY para isso como fizemos com os cards.
Basta passar aquela classe aos elementos que possuírem essas propriedades.

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  flex-wrap: wrap;
Essas duas propriedades também podem entrar no DRY se você quiser. Posteriormente podemos ter que repetir isso, então já podemos criar classes para elas.

`.column {}` e `.wrap {}` que tal?

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.title1 {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 10px;
Por que um texto precisaria de um `height` ? Se você quer mudar o espaçamento de um elemento, usamos `margin`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.text1 {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 45px;
`margin`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.button {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +    font-stretch: condensed;
Qual motivo de utilizar o `font-stretch` ?

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +    background-color: #ffffff;
Quando as letras ou números forem todos iguais, podemos abreviar para `#fff`

`#ffffff` => `#fff`
`#000000` => `#000`
`#aaaaaa` => `#aaa`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.position {
nome da classe

Aqui parece que é uma classe para alterar a `position` de algum elemento e não o nome de uma classe para um elemento.

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.title2 {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  margin-top: 50px;
Vamos começar a tomar cuidado com valores estáticos.
Px é um valor estático porque é imutável, 10px sempre serão 10px.

Pesquise sobre valores dinâmicos em css.
`EM`, `REM`, `VIEW-WIDTH`, `VIEW-HEIGHT` e `%`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  margin-top: 50px;
Se precisarmos alterar isso com `media-queries` vamos ter que alterar sempre os px dos elementos.
Utilizando % ou valores dinâmicos é mais fácil

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.text2 {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.image {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 20vw;
uma imagem não precisa ter width e height setada, apenas uma basta. Geralmente utilizamos width e a altura será ajustada automaticamente

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.nav {
nome da classe e identação

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.navitems {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.navitems-link {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +
remover espaço

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  color: #ffffff;
`#fff`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  background: rgba(0,0, 0, 0.75);
explicite com `background-color`

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.navitems-overlay:hover {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.subtitle {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.subtitle:hover {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.section {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  justify-content: center;
pode usar aquela classe que criamos para reaproveitar

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +  height: 500px;
remover height para trabalharmos com espaçamentos

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.items {
nome da classe e identação

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.image2 {
nome da classe

2021-01-22 18:13 UTC, gqueiroz1 commented on style.css
> +.feature-card {
podemos usar flex para fazer o alinhamento / tamanho dos filhos

2021-01-28 02:59 UTC, gqueiroz1 requested changes

2021-01-28 02:59 UTC, gqueiroz1 commented on css/fonts.css
> +@font-face {
Imagino que seja algo do Visual Studio, mas vamos acertar a identação dessa parte.
Nosso padrão é usar 2 tabs para identar, ele identou com 4

PS: você vai ouvir falar bastante de padrão de código aqui hehe, o code review vai ser bom pra você começar a pegar isso também

2021-01-28 02:59 UTC, gqueiroz1 commented on css/fonts.css
> +    font-weight: 600;
O valor de 600 para o `font-weight` do SemiBold é o que foi utilizado no layout?

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +*,*::after,*::before {
Eu não havia te falado isso mas por padrão costumamos quebrar as linhas de css quando utilizamos elementos seguidos dessa maneira.

```
*,
*::after,
*::before {
  ...
}
```

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +div, article, section, header, footer {
Se eu não me engano todas essas tags já são `display: block` por padrão no css.
Além disso, não é necessário criamos um bloco de código para isso porque com certeza em algum momento estaremos alterando para `display: flex` ou `inline`.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +h1, h2, h3, h4 {
Quebrar as linhas

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  font-family: 'Roboto', sans-serif;
Qual é a fonte que aparece com mais frequência? A fonte padrão do site...
Podemos ver qual é e passar direto no `body`. Dessa forma todos os filhos ficarão com essa fonte e posteriormente alteramos apenas onde é necessário.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  color: #2F362F;
Essa cor é utilizada para todos esses níveis de títulos?

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  margin-bottom: 20px;
Com certeza essa `margin` irá se alterar ao longo do projeto para diferentes títulos ou subtítulos. 
Pode remover daí uma vez que isso além de muito genérico irá ser sobrescrito.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  margin-inline-end: 0px;
Esse tipo de código copiado não tem sentido nem necessidade de estar aqui, provavelmente é algo gerado da biblioteca que o desenvolvedor do layout utilizou.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  font-size: 1.17em;
O mesmo do `display: block` e da `margin` genérica se aplica aqui.. pode remover pelo mesmo motivo.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  margin-inline-end: 0px;
Remover

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
idem aos de cima

Cuidado com coisas muito genéricas. Por exemplo, esse `font-weight: bold` aí.. você concorda que não necessariamente o `h4` é que é `bold` mas sim UM `H4` específico por aí ?
Posso ter um `<h4 class="subtitulo-do-article-XPTO">` sendo bold e também posso ter um `<h4 class="subtitulo-do-article-ABC">` sendo normal.
Ambos são h4, porém um é bold outro não. Então não faz sentido colocar bold para todos os h4.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
idem aos de cima

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
idem

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  vertical-align: middle;
Pq esse vertical-align?

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.width-100 {
Legal, reusabilidade. Parabéns

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
O nome das classes não está condizente com o conteúdo que alteram.
nome `margin-bottom` está alterando `padding`.
Só renomear.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.padding-bottom-120 {
`padding-bottom-127`

mas é necessário ter um valor tão específico assim? é reusado?

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.columns {
qual a finalidade dessa classe?

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
Acho que ficou muito específico pra um nome muito genérico e simples.
`section-white` remete a uma seção que seja branca.. por padrão todo `background` é branco no css, ela seria necessária a menos que precisasse sobrescrever algo.

Além disso, ela altera border e padding, coisas que várias outras seções podem ter iguais mas que não são responsabilidade de uma `.section-white` alterar. Ou que podem ser diferentes apesar de terem um `background-color: #fff` também... Vc não iria conseguir utilizar `.section-white` pra isso.

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
identação

esse `line-height` tá bem grande, isso pode ser feito com `margin`

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.subtitle {
nome da classe genérico

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.button {
nome da classe genérico

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  margin: 10px 10px 0 10px 0;
tem um valor a mais

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.start-creating-and-header-button:hover {
Entendi.. porém seria melhor descrever o comportamento no nome da classe quando é assim.

Se essa shadow for reutilizada em todos os ctas do site poderia ser `cta-default-shadow`

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.header-padding-top {
Isso poderia estar dentro da classe do `header` já que não pode ser reutilizada

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  bottom: 0;
`top: 0` e `left: 0` já resolvem

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.header-launchpage-items {
Melhor ter uma classe que possa ser reutilizada pra isso não acha?

```
.flex-column {
  flex-direction: column;
}
```

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  line-height: 50px;
use margin aqui

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  line-height: 28px;
idem

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  -webkit-text-shadow: 1px 1px rgba(0,0,0,0.5);
não é mais necessário utilizar esses prefixos para a propriedade `text-shadow`.

Esses prefixos servem para garantir que versões mais antigas dos navegadores ou navegadores que ainda tem essa propriedade em fase de teste consigam renderizá-las também.

Você pode ver sobre a compatibilidade de uma determinada propriedade em [https://caniuse.com/](url)

Basta procurar a propriedade e verificar se é compatível com os navegadores ou se ainda precisa de um prefixo para funcionar.

Usando de exemplo a propriedade `flex`
![image](https://user-images.githubusercontent.com/22224160/106082341-4410b180-60f9-11eb-855e-221cc9c7811e.png)
Para o Chrome é possível ver que já é totalmente suportado e que tem uma compatibilidade de 98.93% nos dias atuais (localizado no canto superior direito)
Global	97.22%	+	1.71%	=	98.93%

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  height: 20vw;
não precisa setar height se width já está sendo setado

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  color: #ffffff;
pode encurtar com `color: #fff`

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.imagesfeature-card {
nome grudado

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
por ser uma imagem dentro de um card imagino que ela não precise redimensionar já que o card redimensiona com os breakpoints.
`height: 80px` já resolve, mas melhor usarmos `width` já que não é muito comum setarmos height para esse fim

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  background-color: #ffffff;
para encurtar `background-color: #fff;`
lembrando que sempre que todas as 6 letras ou números forem iguais é possível encurtar usando apenas 3

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  border-radius: 10px 10px;
Já que é igual para ambos os sentidos `border-radius: 10px;`

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  padding: 10px 10px;
idem, encurte com apenas 1 valor

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  border-radius: 10px 10px;
idem apenas 1 valor

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.style-sectionstart-title {
nome grudado

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +.style-sectionstart-subtitle {
nome grudado

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  line-height: 28px;
usar margin para isso

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  padding: 25px 0 25px 0;
como é 25px para cima e para baixo pode refatorar para `padding: 25px 0`

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  background-color: #fff;
background branco já padrão, não precisa passar

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +  color: #ffffff;
encurtar

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +    }
identação

2021-01-28 02:59 UTC, gqueiroz1 commented on css/style.css
> +}
identação

2021-01-28 02:59 UTC, gqueiroz1 commented on index.html
> +</html>
identação

2021-01-28 12:18 UTC, lucasmassei commented on css/fonts.css
> +    font-weight: 600;
Pelo que eu vi não, porém quando fui baixar a font não tinha a medium, ai baixei essa ai pra ver como era

2021-01-28 13:57 UTC, lucasmassei commented on css/style.css
> +  height: 20vw;
Vamos alterar estrutura.

2021-01-28 14:14 UTC, gqueiroz1 approved these changes

2021-01-28 14:14 UTC, merged